FROM wcp-goldeneye-team-docker-virtual.artifactory.swg-devops.com/aquasecurity/trivy:0.19.2
#FROM wcp-goldeneye-team-docker-virtual.artifactory.swg-devops.com/external-secrets/external-secrets:v0.5.8
