name: CI

on:
  workflow_call:

jobs:
  CI_Pipeline:
    runs-on: ubuntu-latest
    container:
      image: icr.io/goldeneye_images/ubi8-cluster-tools@sha256:c731b19a2d8641d0c05f393594e955620502b747d6ad543f7dc7bafbff965ddb
